# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170812_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='path_deploy',
            name='ip_server',
            field=models.CharField(default='192.168.1.101', max_length=200),
        ),
    ]
